package main

// TODO chane this to use the read utf8 charcters!

const (
	// Helper char
	EIA608_CHAR_NULL = ""
	// Basic North American character set
	EIA608_CHAR_SPACE                           = "\x20"
	EIA608_CHAR_EXCLAMATION_MARK                = "\x21"
	EIA608_CHAR_QUOTATION_MARK                  = "\x22"
	EIA608_CHAR_NUMBER_SIGN                     = "\x23"
	EIA608_CHAR_DOLLAR_SIGN                     = "\x24"
	EIA608_CHAR_PERCENT_SIGN                    = "\x25"
	EIA608_CHAR_AMPERSAND                       = "\x26"
	EIA608_CHAR_LEFT_SINGLE_QUOTATION_MARK      = "\xE2\x80\x98"
	EIA608_CHAR_LEFT_PARENTHESIS                = "\x28"
	EIA608_CHAR_RIGHT_PARENTHESIS               = "\x29"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_ACUTE = "\xC3\xA1"
	EIA608_CHAR_PLUS_SIGN                       = "\x2B"
	EIA608_CHAR_COMMA                           = "\x2C"
	EIA608_CHAR_HYPHEN_MINUS                    = "\x2D"
	EIA608_CHAR_FULL_STOP                       = "\x2E"
	EIA608_CHAR_SOLIDUS                         = "\x2F"

	// Basic North American character set
	EIA608_CHAR_DIGIT_ZERO        = "\x30"
	EIA608_CHAR_DIGIT_ONE         = "\x31"
	EIA608_CHAR_DIGIT_TWO         = "\x32"
	EIA608_CHAR_DIGIT_THREE       = "\x33"
	EIA608_CHAR_DIGIT_FOUR        = "\x34"
	EIA608_CHAR_DIGIT_FIVE        = "\x35"
	EIA608_CHAR_DIGIT_SIX         = "\x36"
	EIA608_CHAR_DIGIT_SEVEN       = "\x37"
	EIA608_CHAR_DIGIT_EIGHT       = "\x38"
	EIA608_CHAR_DIGIT_NINE        = "\x39"
	EIA608_CHAR_COLON             = "\x3A"
	EIA608_CHAR_SEMICOLON         = "\x3B"
	EIA608_CHAR_LESS_THAN_SIGN    = "\x3C"
	EIA608_CHAR_EQUALS_SIGN       = "\x3D"
	EIA608_CHAR_GREATER_THAN_SIGN = "\x3E"
	EIA608_CHAR_QUESTION_MARK     = "\x3F"

	// Basic North American character set
	EIA608_CHAR_COMMERCIAL_AT          = "\x40"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A = "\x41"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_B = "\x42"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_C = "\x43"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_D = "\x44"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E = "\x45"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_F = "\x46"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_G = "\x47"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_H = "\x48"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I = "\x49"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_J = "\x4A"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_K = "\x4B"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_L = "\x4C"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_M = "\x4D"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_N = "\x4E"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O = "\x4F"

	// Basic North American character set
	EIA608_CHAR_LATIN_CAPITAL_LETTER_P          = "\x50"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_Q          = "\x51"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_R          = "\x52"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_S          = "\x53"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_T          = "\x54"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U          = "\x55"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_V          = "\x56"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_W          = "\x57"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_X          = "\x58"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_Y          = "\x59"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_Z          = "\x5A"
	EIA608_CHAR_LEFT_SQUARE_BRACKET             = "\x5B"
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_ACUTE = "\xC3\xA9"
	EIA608_CHAR_RIGHT_SQUARE_BRACKET            = "\x5D"
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_ACUTE = "\xC3\xAD"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_ACUTE = "\xC3\xB3"

	// Basic North American character set
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_ACUTE = "\xC3\xBA"
	EIA608_CHAR_LATIN_SMALL_LETTER_A            = "\x61"
	EIA608_CHAR_LATIN_SMALL_LETTER_B            = "\x62"
	EIA608_CHAR_LATIN_SMALL_LETTER_C            = "\x63"
	EIA608_CHAR_LATIN_SMALL_LETTER_D            = "\x64"
	EIA608_CHAR_LATIN_SMALL_LETTER_E            = "\x65"
	EIA608_CHAR_LATIN_SMALL_LETTER_F            = "\x66"
	EIA608_CHAR_LATIN_SMALL_LETTER_G            = "\x67"
	EIA608_CHAR_LATIN_SMALL_LETTER_H            = "\x68"
	EIA608_CHAR_LATIN_SMALL_LETTER_I            = "\x69"
	EIA608_CHAR_LATIN_SMALL_LETTER_J            = "\x6A"
	EIA608_CHAR_LATIN_SMALL_LETTER_K            = "\x6B"
	EIA608_CHAR_LATIN_SMALL_LETTER_L            = "\x6C"
	EIA608_CHAR_LATIN_SMALL_LETTER_M            = "\x6D"
	EIA608_CHAR_LATIN_SMALL_LETTER_N            = "\x6E"
	EIA608_CHAR_LATIN_SMALL_LETTER_O            = "\x6F"

	// Basic North American character set
	EIA608_CHAR_LATIN_SMALL_LETTER_P              = "\x70"
	EIA608_CHAR_LATIN_SMALL_LETTER_Q              = "\x71"
	EIA608_CHAR_LATIN_SMALL_LETTER_R              = "\x72"
	EIA608_CHAR_LATIN_SMALL_LETTER_S              = "\x73"
	EIA608_CHAR_LATIN_SMALL_LETTER_T              = "\x74"
	EIA608_CHAR_LATIN_SMALL_LETTER_U              = "\x75"
	EIA608_CHAR_LATIN_SMALL_LETTER_V              = "\x76"
	EIA608_CHAR_LATIN_SMALL_LETTER_W              = "\x77"
	EIA608_CHAR_LATIN_SMALL_LETTER_X              = "\x78"
	EIA608_CHAR_LATIN_SMALL_LETTER_Y              = "\x79"
	EIA608_CHAR_LATIN_SMALL_LETTER_Z              = "\x7A"
	EIA608_CHAR_LATIN_SMALL_LETTER_C_WITH_CEDILLA = "\xC3\xA7"
	EIA608_CHAR_DIVISION_SIGN                     = "\xC3\xB7"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_N_WITH_TILDE = "\xC3\x91"
	EIA608_CHAR_LATIN_SMALL_LETTER_N_WITH_TILDE   = "\xC3\xB1"
	EIA608_CHAR_FULL_BLOCK                        = "\xE2\x96\x88"

	// Special North American character set[edit]
	EIA608_CHAR_REGISTERED_SIGN                      = "\xC2\xAE"
	EIA608_CHAR_DEGREE_SIGN                          = "\xC2\xB0"
	EIA608_CHAR_VULGAR_FRACTION_ONE_HALF             = "\xC2\xBD"
	EIA608_CHAR_INVERTED_QUESTION_MARK               = "\xC2\xBF"
	EIA608_CHAR_TRADE_MARK_SIGN                      = "\xE2\x84\xA2"
	EIA608_CHAR_CENT_SIGN                            = "\xC2\xA2"
	EIA608_CHAR_POUND_SIGN                           = "\xC2\xA3"
	EIA608_CHAR_EIGHTH_NOTE                          = "\xE2\x99\xAA"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_GRAVE      = "\xC3\xA0"
	EIA608_CHAR_NO_BREAK_SPACE                       = "\xC2\xA0"
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_GRAVE      = "\xC3\xA8"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX = "\xC3\xA2"
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX = "\xC3\xAA"
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX = "\xC3\xAE"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX = "\xC3\xB4"
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX = "\xC3\xBB"

	// Extended Western European character set : Extended Spanish/Miscellaneous
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_ACUTE     = "\xC3\x81"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_ACUTE     = "\xC3\x89"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_ACUTE     = "\xC3\x93"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_ACUTE     = "\xC3\x9A"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS = "\xC3\x9C"
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_DIAERESIS   = "\xC3\xBC"
	EIA608_CHAR_RIGHT_SINGLE_QUOTATION_MARK           = "\xE2\x80\x99"
	EIA608_CHAR_INVERTED_EXCLAMATION_MARK             = "\xC2\xA1"
	EIA608_CHAR_ASTERISK                              = "\x2A"
	EIA608_CHAR_APOSTROPHE                            = "\x27"
	EIA608_CHAR_EM_DASH                               = "\xE2\x80\x94"
	EIA608_CHAR_COPYRIGHT_SIGN                        = "\xC2\xA9"
	EIA608_CHAR_SERVICE_MARK                          = "\xE2\x84\xA0"
	EIA608_CHAR_BULLET                                = "\xE2\x80\xA2"
	EIA608_CHAR_LEFT_DOUBLE_QUOTATION_MARK            = "\xE2\x80\x9C"
	EIA608_CHAR_RIGHT_DOUBLE_QUOTATION_MARK           = "\xE2\x80\x9D"

	// Extended Western European character set : Extended French
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_GRAVE          = "\xC3\x80"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX     = "\xC3\x82"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA        = "\xC3\x87"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_GRAVE          = "\xC3\x88"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX     = "\xC3\x8A"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS      = "\xC3\x8B"
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_DIAERESIS        = "\xC3\xAB"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX     = "\xC3\x8E"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS      = "\xC3\x8F"
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_DIAERESIS        = "\xC3\xAF"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX     = "\xC3\x94"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_GRAVE          = "\xC3\x99"
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_GRAVE            = "\xC3\xB9"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX     = "\xC3\x9B"
	EIA608_CHAR_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK  = "\xC2\xAB"
	EIA608_CHAR_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK = "\xC2\xBB"

	// Extended Western European character set : Portuguese
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_TILDE = "\xC3\x83"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_TILDE   = "\xC3\xA3"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_ACUTE = "\xC3\x8D"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_GRAVE = "\xC3\x8C"
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_GRAVE   = "\xC3\xAC"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_GRAVE = "\xC3\x92"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_GRAVE   = "\xC3\xB2"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_TILDE = "\xC3\x95"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_TILDE   = "\xC3\xB5"
	EIA608_CHAR_LEFT_CURLY_BRACKET                = "\x7B"
	EIA608_CHAR_RIGHT_CURLY_BRACKET               = "\x7D"
	EIA608_CHAR_REVERSE_SOLIDUS                   = "\x5C"
	EIA608_CHAR_CIRCUMFLEX_ACCENT                 = "\x5E"
	EIA608_CHAR_LOW_LINE                          = "\x5F"
	EIA608_CHAR_VERTICAL_LINE                     = "\x7C"
	EIA608_CHAR_TILDE                             = "\x7E"

	// Extended Western European character set : German/Danish
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS  = "\xC3\x84"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_DIAERESIS    = "\xC3\xA4"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS  = "\xC3\x96"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_DIAERESIS    = "\xC3\xB6"
	EIA608_CHAR_LATIN_SMALL_LETTER_SHARP_S             = "\xC3\x9F"
	EIA608_CHAR_YEN_SIGN                               = "\xC2\xA5"
	EIA608_CHAR_CURRENCY_SIGN                          = "\xC2\xA4"
	EIA608_CHAR_BROKEN_BAR                             = "\xC2\xA6"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE = "\xC3\x85"
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE   = "\xC3\xA5"
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_STROKE     = "\xC3\x98"
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_STROKE       = "\xC3\xB8"
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT      = "\xE2\x94\x8C" // top left
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT       = "\xE2\x94\x90" // top right
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_UP_AND_RIGHT        = "\xE2\x94\x94" // lower left
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_UP_AND_LEFT         = "\xE2\x94\x98" // bottom right
)

var charMap = []string{
	" ", "!", "'", "#", "$", "%", "&",
	EIA608_CHAR_RIGHT_SINGLE_QUOTATION_MARK,
	"(", ")",
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_ACUTE,
	"+", ",",
	EIA608_CHAR_HYPHEN_MINUS,
	EIA608_CHAR_FULL_STOP,
	EIA608_CHAR_SOLIDUS,
	"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ":", ";", "<", "=", ">", "?", "@",
	"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
	"[",
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_ACUTE,
	"]",
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_ACUTE,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_ACUTE,
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_ACUTE,
	"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
	EIA608_CHAR_LATIN_SMALL_LETTER_C_WITH_CEDILLA,
	EIA608_CHAR_DIVISION_SIGN,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_N_WITH_TILDE,
	EIA608_CHAR_LATIN_SMALL_LETTER_N_WITH_TILDE,
	EIA608_CHAR_FULL_BLOCK,
	EIA608_CHAR_REGISTERED_SIGN,
	EIA608_CHAR_DEGREE_SIGN,
	EIA608_CHAR_VULGAR_FRACTION_ONE_HALF,
	EIA608_CHAR_INVERTED_QUESTION_MARK,
	EIA608_CHAR_TRADE_MARK_SIGN,
	EIA608_CHAR_CENT_SIGN,
	EIA608_CHAR_POUND_SIGN,
	EIA608_CHAR_EIGHTH_NOTE,
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_GRAVE,
	EIA608_CHAR_NO_BREAK_SPACE,
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_GRAVE,
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_ACUTE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_ACUTE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_ACUTE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_ACUTE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_DIAERESIS,
	EIA608_CHAR_LEFT_SINGLE_QUOTATION_MARK,
	EIA608_CHAR_INVERTED_EXCLAMATION_MARK,
	"*",
	"'",
	EIA608_CHAR_EM_DASH,
	EIA608_CHAR_COPYRIGHT_SIGN,
	EIA608_CHAR_SERVICE_MARK,
	EIA608_CHAR_BULLET,
	EIA608_CHAR_LEFT_DOUBLE_QUOTATION_MARK,
	EIA608_CHAR_RIGHT_DOUBLE_QUOTATION_MARK,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_GRAVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_C_WITH_CEDILLA,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_GRAVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_E_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_GRAVE,
	EIA608_CHAR_LATIN_SMALL_LETTER_U_WITH_GRAVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX,
	EIA608_CHAR_LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK,
	EIA608_CHAR_RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_TILDE,
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_TILDE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_ACUTE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_I_WITH_GRAVE,
	EIA608_CHAR_LATIN_SMALL_LETTER_I_WITH_GRAVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_GRAVE,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_GRAVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_TILDE,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_TILDE,
	"{",
	"}",
	EIA608_CHAR_REVERSE_SOLIDUS,
	EIA608_CHAR_CIRCUMFLEX_ACCENT,
	"_",
	"|",
	"~",
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_DIAERESIS,
	EIA608_CHAR_LATIN_SMALL_LETTER_SHARP_S,
	EIA608_CHAR_YEN_SIGN,
	EIA608_CHAR_CURRENCY_SIGN,
	EIA608_CHAR_BROKEN_BAR,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE,
	EIA608_CHAR_LATIN_SMALL_LETTER_A_WITH_RING_ABOVE,
	EIA608_CHAR_LATIN_CAPITAL_LETTER_O_WITH_STROKE,
	EIA608_CHAR_LATIN_SMALL_LETTER_O_WITH_STROKE,
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_RIGHT,
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_DOWN_AND_LEFT,
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_UP_AND_RIGHT,
	EIA608_CHAR_BOX_DRAWINGS_LIGHT_UP_AND_LEFT,
}
